backend/backend/urls.py
import accounts.views
import currencies.views
import users.views
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r"accounts", accounts.views.AccountView, "account")
router.register(r"transactions", accounts.views.TransactionView, "transaction")
router.register(r"users", users.views.UserView, "user")
router.register(r"currencies", currencies.views.CurrencyView, "currency")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include(router.urls)),
]

backend/accounts/models.py
from currencies.models import Currency
from django.db import models
from django.db.models import Sum
from django.db.utils import IntegrityError
from django.utils.translation import gettext_lazy as _
from users.models import User

from .utils import ofxutils, uuid


class AccountType(models.IntegerChoices):
    UNKNOWN = 1, _("Unknown")
    BANK = 2, _("Bank Account")
    CREDIT = 3, _("Credit Card")
    CASH = 4, _("Cash")


class Account(models.Model):
    user = models.ForeignKey(
        User,
        models.CASCADE,
        verbose_name="Owner of the account.",
    )
    currency = models.ForeignKey(
        Currency,
        models.PROTECT,
        verbose_name="Currency of the account.",
        blank=True,
    )
    name = models.CharField(
        max_length=128,
        verbose_name="Name of the account.",
    )

    account_type = models.IntegerField(choices=AccountType, default=AccountType.UNKNOWN)

    def __str__(self) -> str:
        return "{} ({})".format(self.name, self.currency.identifier)

    def get_balance(self):
        transactions = self.transaction_set.all()
        return transactions.aggregate(balance=Sum("value", default=0))["balance"]

    @classmethod
    def create_from_file(cls, user: User, filetype: str, content: str, **kwargs):
        """_summary_

        Args:
            user (User): _description_
            filename (str): _description_

        Raises:
            FileNotFoundError: _description_
            NotImplementedError: _description_

        Returns:
            _type_: _description_
        """
        if filetype == "ofx":
            account, transactions = cls.from_ofx_file(content, **kwargs)
        else:
            raise NotImplementedError(
                "File extension not supported: {}".format(filetype)
            )

        account.user = user
        account.save()
        for transaction in transactions:
            try:
                transaction.save()
            except IntegrityError:
                continue

        return account

    def update_from_file(self, filetype: str, content: str, **kwargs):
        """_summary_

        Args:
            user (User): _description_
            filename (str): _description_

        Raises:
            FileNotFoundError: _description_
            NotImplementedError: _description_

        Returns:
            _type_: _description_
        """
        if filetype == "ofx":
            transactions = self.transactions_from_ofx_file(content, **kwargs)
        else:
            raise NotImplementedError(
                "File extension not supported: {}".format(filetype)
            )

        written_transactions = []
        for transaction in transactions:
            try:
                transaction.save()
                written_transactions.append(transaction)
            except IntegrityError:
                continue

        return written_transactions

    def transactions_from_ofx_file(self, content: str, **kwarg):
        """_summary_

        Args:
            user (User): _description_
            filename (Path): _description_
        """
        data = ofxutils.OfxData.from_file(content)
        transactions = [
            Transaction.from_ofx_data(transaction, self)
            for transaction in data.transactions
        ]
        return transactions

    @classmethod
    def from_ofx_file(cls, content: str, **kwarg):
        """_summary_

        Args:
            user (User): _description_
            filename (Path): _description_
        """
        data = ofxutils.OfxData.from_file(content)
        account = cls.from_ofx_data(data.account, **kwarg)
        transactions = [
            Transaction.from_ofx_data(transaction, account)
            for transaction in data.transactions
        ]
        return account, transactions

    @classmethod
    def from_ofx_data(
        cls,
        data: dict,
        currency: Currency = Currency(identifier="USD"),
        name: str = None,
    ):
        """_summary_

        Args:
            user (User): _description_
            data (ofxutils.OfxData): _description_
            currency (str, optional): _description_. Defaults to "USD".
            name (str, optional): _description_. Defaults to None.

        Returns:
            Account: _description_
        """
        account = cls(
            currency=currency,
            name=name if name is not None else data["institution"],
            account_type=data["type"] + 1,
        )
        return account


class Transaction(models.Model):
    account = models.ForeignKey(
        Account,
        models.CASCADE,
        verbose_name="The account on which this transaction was operated.",
    )
    # category = models.ForeignKey(
    #     "categories.Category",
    #     models.RESTRICT,
    # )
    payee = models.CharField(max_length=128)
    memo = models.CharField(max_length=128)
    value = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    transaction_hash = models.UUIDField(editable=False, unique=True)

    def __str__(self) -> str:
        return "{} - {} ({} {})".format(
            self.date, self.payee, self.value, self.account.currency.symbol
        )

    def get_hash(self):
        content = str(self.account.id) + self.payee + str(self.value) + str(self.date)
        return uuid.create_uuid_from_string(content)

    def save(self, *args, **kwargs):
        self.transaction_hash = self.get_hash()
        super().save(*args, **kwargs)

    @classmethod
    def from_ofx_data(cls, data: dict, account: Account):
        """_summary_

        Args:
            data (dict): _description_
            account (Account | None, optional): _description_. Defaults to None.

        Returns:
            Transaction: _description_
        """
        transaction_value = data["amount"]

        if account.account_type == AccountType.CREDIT:
            if data["type"] == "credit":
                transaction_value = -transaction_value
        else:
            if data["type"] == "debit":
                transaction_value = -transaction_value

        transaction = cls(
            account=account,
            payee=data["payee"],
            memo=data["memo"],
            date=data["user_date"].date(),
            value=transaction_value,
        )
        return transaction

backend/accounts/views.py
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.filters import OrderingFilter
from rest_framework.response import Response

from .models import Account, Transaction
from .serializers import AccountSerializer, OfxSerializer, TransactionSerializer


class AccountView(viewsets.ModelViewSet):
    serializer_class = AccountSerializer
    queryset = Account.objects.all()

    @action(detail=False, methods=["post"])
    def create_from_ofx(self, request) -> Response:
        serializer = OfxSerializer(data=request.data)
        if serializer.is_valid():
            content = serializer.validated_data["content"]
            user = serializer.validated_data["user"]
            account = Account.create_from_file(user, "ofx", content)
            return Response(AccountSerializer(account).data)
        else:
            return Response(serializer.errors)

    @action(detail=True, methods=["post"])
    def update_from_ofx(self, request, pk=None) -> Response:
        account = self.get_object()
        serializer = OfxSerializer(data=request.data)
        if serializer.is_valid():
            if serializer.validated_data["user"].id == account.user.id:
                content = serializer.validated_data["content"]
                transactions = account.update_from_file("ofx", content)
                return Response(TransactionSerializer(transactions, many=True).data)
            else:
                return Response(
                    {"user": "The provided user does not match the targeted account."}
                )
        else:
            return Response(serializer.errors)


class TransactionView(viewsets.ModelViewSet):
    serializer_class = TransactionSerializer
    queryset = Transaction.objects.all()
    filter_backends = [OrderingFilter, DjangoFilterBackend]
    filterset_fields = ("account",)
    ordering_fields = ("date", "value", "payee")

backend/accounts/templates/accounts/account_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank Account Information</title>
    <style>
        body, html {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            overflow-x: hidden;
        }
        .account-details {
            width: 100%;
            display: flex;
            justify-content: space-around;
            margin-bottom: 20px;
        }
        .account-details div {
            margin-right: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .transactions-table {
            width: 100%;
            max-height: 70vh;
            overflow-y: auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="account-details">
            <div>
                <strong>Owner:</strong> {{account.user.firstName}} {{account.user.lastName}}
            </div>
            <div>
                <strong>Organization:</strong> {{account.name}}
            </div>
            <div>
                <strong>Account Type:</strong> {{account.get_account_type_display}}
            </div>
            <div>
                <strong>Balance:</strong> {{balance}} {{account.currency.symbol}}
            </div>
        </div>
        <h2>Most Recent Transactions</h2>
        <div class="transactions-table">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Date</th>
                        <th>Payee</th>
                        <th>Memo</th>
                        <th>Credit</th>
                        <th>Debit</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaction in account.transaction_set.all %}
                        <tr>
                            <td><a href="{% url 'accounts:transaction_detail' account.id transaction.id %}">{{transaction.id}}</a></td>
                            <td>{{transaction.date}}</td>
                            <td>{{transaction.payee}}</td>
                            <td>{{transaction.memo}}</td>
                            <td>{% if transaction.value >= 0 %}{{ transaction.value}} {{account.currency.symbol}}{% endif %}</td>
                            <td>{% if transaction.value < 0 %}{{ transaction.value }} {{account.currency.symbol}}{% endif %}</td>
                        </tr>
                    </a>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>